### PR TITLE
fix problem with Monolog integration

### PR DESCRIPTION
**Pull request by kamilsk**
https://github.com/jolicode/JoliNotif/issues/24

### CODE REVIEW

**Comment by kamilsk** [comment]
`Symfony\Component\Process\ProcessUtils::escapeArgument()` not work unfortunately

**Comment by kamilsk** [comment]
test fails before: https://travis-ci.org/jolicode/JoliNotif/builds/113865940

**Comment by pyrech** [comment]
Thanks for the PR. You updated the test but I'm not sure these new command lines work. I just tried to manually run a sample and it failed:
`"'osascript' '-e' 'display notification \"I\'\''m the notification body\" with title \"I\'\''m the notification title\"'"` 
will be outputted like
`'osascript' '-e' 'display notification "I\'\''m the notification body" with title "I\'\''m the notification title"'`
and this last one triggers a syntax error.

**Comment by kamilsk** [comment]
Tested on
```
iMac-Kamil:Development kamil$ php -v
PHP 5.5.33 (cli) (built: Mar 11 2016 16:55:00)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

```
iMac-Kamil:Development kamil$ brew unlink php55
Unlinking /usr/local/Cellar/php55/5.5.33... 20 symlinks removed
iMac-Kamil:Development kamil$ brew link php56
Linking /usr/local/Cellar/php56/5.6.19... 17 symlinks created
iMac-Kamil:Development kamil$ php -v
PHP 5.6.19 (cli) (built: Mar 11 2016 17:06:48)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

```
iMac-Kamil:Development kamil$ brew unlink php56 && brew link php70
Unlinking /usr/local/Cellar/php56/5.6.19... 20 symlinks removed
Linking /usr/local/Cellar/php70/7.0.4... 17 symlinks created
iMac-Kamil:Development kamil$ php -v
PHP 7.0.4 (cli) (built: Mar 11 2016 17:17:36) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

~~~

```
/usr/bin/php /private/var/folders/29/_ttmbnj17rs94gt1x8t88mn40000gn/T/ide-phpunit.php --configuration /Users/kamil/Development/JoliNotif/phpunit.xml.dist Joli\JoliNotif\tests\Notifier\AppleScriptNotifierTest /Users/kamil/Development/JoliNotif/tests/Notifier/AppleScriptNotifierTest.php
Testing started at 16:13 ...
#!/usr/bin/env php
PHPUnit 4.8.24 by Sebastian Bergmann and contributors.

.........

Time: 635 ms, Memory: 5.75Mb

OK (9 tests, 9 assertions)

Process finished with exit code 0
```

**Comment by kamilsk** [comment]
your master not stable after "Merge pull request #23 from raphaelcsilva/master"

**Comment by pyrech** [comment]
Yes, I know that phar is broken on travis. But here I'm not talking about tests but only about the generated commands that looks broken to me. Did you try to manually run one of the expected command?

For information, our phpunit tests ensure that generated commands are the ones expected (those comming from the `getExpectedCommandLineForNotificationXXX()` methods) but you have to be sure that the expected command themselves works because travis cannot run MacOS scripts, nor Windows ones. I hope I'm clear in my explanations.

**Comment by kamilsk** [comment]
Yeah, I got it, will try to check.

**Comment by kamilsk** [comment]
@pyrech, you are right, it didn't work and I rewrite it

Checked by this code:

```php
require __DIR__ . '/vendor/autoload.php';

use Joli\JoliNotif\Notification;
use Joli\JoliNotif\NotifierFactory;

$notifier = NotifierFactory::create();
if ($notifier) {
    $notifier->send(
        (new Notification())
            ->setBody('I\'m the notification body')
    );
    sleep(1);
    $notifier->send(
        (new Notification())
            ->setBody('I\'m the notification body')
            ->setTitle('I\'m the notification title')
    );
    sleep(1);
    $notifier->send(
        (new Notification())
            ->setBody('I\'m the notification body')
            ->setTitle('I\'m the notification title')
            ->setIcon('/home/toto/Images/my-icon.png')
    );
    sleep(1);
    $notifier->send(
        (new Notification())
            ->setBody('[2016-03-15 14:17:21] test.INFO: test [] {"time_execution":"0.000"}')
    );
    sleep(1);
    $notifier->send(
        (new Notification())
            ->setBody("[2016-03-15 14:17:21] test.INFO: test [] {\"time_execution\":\"0.000\"}")
    );
}
```

**Comment by kamilsk** [comment]
@pyrech, I think that `$body = 'some text with "quotes"'` is valid string and should work. But now it is not and I fixed it. Do you have any suggestions?

**Comment by pyrech** [comment]
:+1: Thank you!

**Pull request merged**
