### PR TITLE
feat(driver): Sound option with TerminalNotifierDriver

### PR DESCRIPTION
**Pull request by aurac**

### CODE REVIEW

**Comment by lyrixx** [comment]
Hello. Thanks for your first contribution 💛

I like it! (This project is going wild 😅)

It seems this PR breaks some CI tests. Could you have a look at it?

Could you also add a note in the CHANGELOG?

And I'm not sure, but I may deserve a [doc](https://github.com/jolicode/JoliNotif/tree/main/doc)  entry

**Comment by aurac** [comment]
Hello !

I added some documentation to inform that TerminalNotifierDriver now supports the sound option but I don't see in the doc where I could add an entire entry

**Comment by pyrech** [comment]
Your contribution looks good to me and the doc you updated is enough. BUT you edited the wrong chapter (`Subtitle` instead of `Sound`) :sweat_smile: 

I will merge your PR as soon this is fixed :wink:

**Comment by aurac** [comment]
My bad 😅 I fixed it

**Pull request merged**
